name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: ghostshreyash  # Replace with your GitHub username
          svg_out_path: dist/snake.svg

      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output  # Push the SVG to the 'output' branch
          force: true
